#! /bin/bash

set -e

rm -f  a b c d e f g h
mkfifo a b c d e f g h

mem_used() {
    free -h | awk '/^Mem:/ {printf "%s / %s\n", $3, $2; exit 0}'
}

disk_rem() {
    df -h / | awk 'NR == 2 {printf "%s / %s\n", $3, $2; exit 0}'
}

loadavg() {
    cat /proc/loadavg
}

while :; do echo $((i++)) > a; sleep 1; done &
while :; do mem_used      > b; sleep 1; done &
while :; do disk_rem      > c; sleep 1; done &
while :; do loadavg       > d; sleep 1; done &
echo  'will expire'       > e &
(echo 'will error'        > f; sleep 1; rm f) &
while :; do date          > g; sleep 1; done &
echo  'never exprires'    > h &

./pista \
    -l 0 \
    -i 0 \
    a  5 2 \
    b 15 2 \
    c 15 2 \
    d 30 2 \
    e 15 5 \
    f 15 2 \
    g 30 2 \
    h 15 -1
