#! /bin/bash

set -e

DEFAULT_DIR=~/.pistactl
DEFAULT_SESSION=pistactl
DEFAULT_SLOT_TTL=5
DEFAULT_PISTA_OPTS="-l 3 -i 0 -f ' (' -s ')    (' -r ') ' -x"

counter_next() {
    local -r file="$_counter_file"

    awk '{n = $1} END {print n + 1}' "$file" | sponge "$file"
    cat "$file"
}

assert_file_not_empty() {
    local -r path="$1"

    if [ ! -s "$path" ]
    then
        printf '[error] file missing or empty: "%s"\n' "$path" >&2
        exit 1
    fi
}

assert_file_executable() {
    local -r path="$1"

    if [ ! -x "$path" ]
    then
        printf '[error] file missing or not executable: "%s"\n' "$path" >&2
        exit 1
    fi
}

from_file_or_default() {
    local -r file="$1"
    local -r default="$2"
    local value

    if [ -s "$file" ]
    then
        value=$(< "$file")
    else
        value="$default"
    fi
    echo "$value"
}

from_file_with_assert() {
    local -r file="$1"

    assert_file_not_empty "$file"
    cat "$file"
}

tmux_new_win() {
    local -r cmd="$1"

    local -r window=$(counter_next "$_counter_file")
    local -r pane=0

    echo "[debug] window:\"$window\" cmd:\"$cmd\"" >&2
    $_tmux new-window -t "$_session"
    $_tmux send-keys  -t "$_session":"$window"."$pane" "$cmd" ENTER
}

start_slot() {
    local -r dir_slot="$1"

    local -r name=$(basename "$dir_slot")
    local -r out_pipe="$dir_slot"/out
    local -r run_file="$dir_slot"/run
    local -r len_file="$dir_slot"/len
    local -r ttl_file="$dir_slot"/ttl
    local -r len=$(from_file_with_assert "$len_file")
    local -r ttl=$(from_file_or_default "$ttl_file" "$DEFAULT_SLOT_TTL")

    assert_file_not_empty "$run_file"
    assert_file_executable "$run_file"

    rm -f "$out_pipe"
    mkfifo "$out_pipe"
    tmux_new_win "cd $dir_slot && $run_file > $out_pipe; notify-send -u critical 'pista slot exited!' \"$name\n\$?\""
    printf '%s %d %d\n' "$out_pipe" "$len" "$ttl"
}

start_slots() {
    local dir_slot

    list_slots \
    | while read -r dir_slot; do
        start_slot "$dir_slot"
    done \
    | xargs
}

list_slots() {
    find "$_dir_slots" -mindepth 1 -maxdepth 1 -type d | sort
}

remove_slot_pipes() {
    find "$_dir_slots" -type p -delete
}

_start() {
    local -r opts=$(from_file_or_default "$_dir"/options "$DEFAULT_PISTA_OPTS")

    mkdir -p "$_dir_slots"

    $_tmux new-session -d -s "$_session"

    # Have to increment window ids in a file, because an increment operation
    # would be executed local to each subprocess if we did something like:
    #     $(start_slot $((win++)) foo)
    _counter_file=$(mktemp)
    tmux_new_win \
        "pista $opts $(start_slots); notify-send -u critical 'pista exited!' \"\$?\""
    rm "$_counter_file"
}

_stop() {
    $_tmux kill-session -t "$_session"
    remove_slot_pipes
}

_restart() {
    _stop || true
    _start
}

_attach() {
    $_tmux attach -t "$_session"
}

main() {
    local -r program="$0"
    local -r arg_cmd="$1"
    local -r arg_dir="$2"

    local cmd

    case "$arg_cmd" in
        'start'   ) cmd=_start;;
        'stop'    ) cmd=_stop;;
        'restart' ) cmd=_restart;;
        'attach'  ) cmd=_attach;;
        'help')
            echo "$program (start|stop|restart|attach|help) [DIRECTORY]" >&2
            exit 1;;
        '')
            echo "[error] No command given." >&2
            exit 1;;
        *)
            echo "[error] Unknown command: \"$arg_cmd\". Known: start|stop|restart|attach" >&2
            exit 1;;
    esac
    case "$arg_dir" in
        '')
            _dir="$DEFAULT_DIR";;
        *)
            _dir="$arg_dir";;
    esac

    local -r session_name_file="$_dir"/session
    if [ -s "$session_name_file" ]
    then
        _session=$(< "$session_name_file")
    else
        _session="$DEFAULT_SESSION"
    fi

    _dir_slots="$_dir"/slots
    _tmux="tmux -L $_session"

    mkdir -p "$_dir"
    cd "$_dir"
    $cmd
}

main "$@"
